---
- name: deploy ec2 stuff for workshop
  hosts: localhost

  tasks:
    - name: deploy ec2 master instances
      ec2:
        key_name: nate-key
        instance_type: m4.xlarge
        image: ami-40603AD1
        wait: yes
        group: ['ocp-node', 'ocp-master']
        instance_tags:
            type: master-node
            Name: ocp-master-{{ student_id }}1
        exact_count: 1
        count_tag: master-node
        vpc_subnet_id: subnet-7414a13c
        assign_public_ip: yes
      register: master_nodes

    - name: deploy ec2 node instances
      ec2:
        key_name: nate-key
        instance_type: t2.large
        image: ami-40603AD1
        wait: yes
        group: ['ocp-node', 'ocp-infranode']
        instance_tags:
            type: app-node
            Name: ocp-node-{{ student_id }}{{ item }}
        exact_count: 3
        count_tag: app-node
        vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes
      with_sequence: count=3
      register: app_nodes

    - name: create temp inventories
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: all_nodes
      with_items:
        - "{{ master_nodes.instances }}"
        - "{{ app_nodes.instances }}"

    - debug:
        var: master_nodes

    - debug:
        var: app_nodes

    - name: update route53
      route53:
        state: present
        zone: openshift.stencell.net
        record: "{{ item.name }}"
        value: "{{ item.public_ip }}"
        type: A
        ttl: 300
      with_items:
        - "{{ master_nodes.instances }}"
        - "{{ app_nodes.instances }}"

- name: prep hosts
  hosts: all_nodes

  tasks:
    - include: ../register_rhn.yml
    - include: ../install_ocp_packages.yml
