---
- name: deploy ec2 stuff for workshop
  hosts: localhost

  tasks:
    - name: deploy ec2 master instances
      ec2:
        key_name: nate-key
        instance_type: m4.xlarge
        image: ami-bd3f94c5
        wait: yes
        group: ['ocp_node', 'ocp_master']
        instance_tags:
            type: master-node
            Name: ocp-master-{{ student_id }}1
        exact_count: 1
        count_tag: master-node
        vpc_subnet_id: subnet-7414a13c
        assign_public_ip: yes
        region: us-west-2
        volumes:
          - device_name: /dev/xvdb
            volume_type: gp2
            volume_size: 20
            delete_on_termination: true
          - device_name: /dev/xvdc
            volume_type: gp2
            volume_size: 60
            delete_on_termination: true
      register: master_nodes

    - name: deploy ec2 node instances
      ec2:
        key_name: nate-key
        instance_type: t2.large
        image: ami-bd3f94c5
        wait: yes
        group: ['ocp_node', 'ocp_infranode']
        instance_tags:
            type: app-node
            Name: ocp-node-{{ student_id }}{{ item }}
        #exact_count: 3
        count_tag: app-node
        vpc_subnet_id: subnet-7414a13c
        assign_public_ip: yes
        region: us-west-2
        volumes:
          - device_name: /dev/xvdb
            volume_type: gp2
            volume_size: 20
            delete_on_termination: true
      with_sequence: count=3
      register: app_nodes

    # - debug:
    #     var: master_nodes
    #
    # - debug:
    #     var: app_nodes

    - name: create temp inventories - masters
      add_host:
        hostname: "{{ item.tags.Name }}.openshift.stencell.net"
        ansible_host: "{{ item.public_ip }}"
        groupname:
          - all_nodes
          - masters
      with_items: "{{ master_nodes.instances }}"

    - name: create temp inventories - nodes
      add_host:
        hostname: "{{ item['instances'][0]['tags']['Name'] }}.openshift.stencell.net"
        ansible_host: "{{ item['instances'][0]['public_ip'] }}"
        groupname:
          - all_nodes
          - nodes
      with_items: "{{ app_nodes.results }}"

    - debug:
        var: groups['masters']

    - name: update route53 for master
      route53:
        state: present
        zone: openshift.stencell.net
        record: "{{ item.tags.Name }}.openshift.stencell.net"
        value: "{{ item.public_ip }}"
        type: A
        ttl: 300
        overwrite: true
      with_items: "{{ master_nodes.instances }}"

    - name: update route53 for nodes
      route53:
        state: present
        zone: openshift.stencell.net
        record: "{{ item['instances'][0]['tags']['Name'] }}.openshift.stencell.net"
        value: "{{ item['instances'][0]['public_ip'] }}"
        type: A
        ttl: 300
        overwrite: true
      with_items: "{{ app_nodes.results }}"

    - name: wait for server to be available
      wait_for:
        host: "{{ item }}"
        state: started
        delay: 15
        timeout: 300
        port: 22
      with_items: "{{ groups.all_nodes }}"
      become: false
      delegate_to: localhost

- name: prep hosts
  hosts: all_nodes
  become: true
  user: ec2-user
  #gather_facts: false

  tasks:
    - include: ../register_rhn.yml
    - include: ../install_ocp_packages.yml

- name: set up PV storage on master
  hosts: masters
  user: ec2-user
  become: true

  tasks:
    - name: set up PV storage on master node
      lvol:
        vg: vg-storage
        lv: lv-storage
        pvs: /dev/xvdc
        size: 100%FREE

- name: create openshift inventory file
  hosts: localhost

  tasks:
    - name: create openshift inventory file
      template:
        dest: ./{{ student_id }}-ocp-inventory
        src: ocp-inventory.j2
