---
- name: Playbook to update r53 records
  hosts: localhost

  tasks:
    - ec2_instance_facts:
        region: us-west-2
        filters:
          "tag:function": openshift
      register: ec2_instances

    - debug:
        var: ec2_instances

    - route53:
        state: present
        zone: openshift.stencell.net
        record: "{{ item.tags.Name }}.openshift.stencell.net"
        value: "{{ item.public_ip_address }}"
        type: A
        ttl: 300
        overwrite: true
        wait: yes
      with_items: "{{ ec2_instances.instances }}"
