---
- name: Playbook to update r53 records
  hosts: localhost

  tasks:
    - ec2_instance_facts:
        region: us-west-2
        filters:
          "tag:Name": "{{ item }}"
      register: ec2_instances
      with_items:
        - ocp-master-{{ student_id }}-1
        - ocp-node-{{ student_id }}-1
        - ocp-node-{{ student_id }}-2
        - ocp-node-{{ student_id }}-3
        - ocp-infra-{{ student_id }}-1
        - ocp-infra-{{ student_id }}-2
        - ocp-infra-{{ student_id }}-3

    - debug:
        var: ec2_instances

    - route53:
        state: present
        zone: openshift.stencell.net
        record: "{{ item['instances'][0]['tags']['Name'] }}.{{ dns_zone }}"
        value: "{{ item['instances'][0]['public_ip_address'] }}"
        type: A
        ttl: 300
        overwrite: true
      with_items: "{{ ec2_instances.results }}"
